# Site settings
title: Akos Gintl blog
email: 
description: "this is my blog"
baseurl: ""
url: "http://akosgintl.github.io"
# twitter_username: ...
github_username:  akosgintl

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
